using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace SoqlGen.Sources;

internal static partial class Texts
{
    public const string SoqlFieldAttribute = $$"""
    // <auto-generated />
    // Generated by SoqlGen
    
    namespace {{nameof(SoqlGen)}};

    #nullable enable
    [System.AttributeUsage(System.AttributeTargets.Property, AllowMultiple = true)]
    public sealed class {{nameof(SoqlFieldAttribute)}} : System.Attribute
    {
        public {{nameof(SoqlFieldAttribute)}}(string fieldName, string key)
        {
            FieldName = fieldName;
            Key = key;
        }

        public string FieldName { get; }
        public string Key { get; }
    }
    """;

    public static InitializationContext AddSoqlFieldAttributeSource(this InitializationContext ctx)
    {
        ctx.AddSource($"{nameof(SoqlFieldAttribute)}.g.cs", SourceText.From(SoqlFieldAttribute, Encoding.UTF8));
        return ctx;
    }
}
