using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace SoqlGen.Sources;

internal static partial class Texts
{
    public static InitializationContext AddSerializationHelpersSource(this InitializationContext ctx)
    {
        var source = $$"""
        // <auto-generated />
        // Generated by SoqlGen
        using System.Text.Json;

        namespace {{nameof(SoqlGen)}}
        {
            public static class SerializationHelpers
            {
                public static void TrySkip(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.StartObject || reader.TokenType == JsonTokenType.StartArray)
                    {
                        reader.Skip();
                    }
                }

                public static T[] ReadPrimitiveArray<T>(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.Null) return null;
                    if (reader.TokenType != JsonTokenType.StartArray) 
                    {
                        TrySkip(ref reader);
                        return null;
                    }

                    var list = new System.Collections.Generic.List<T>();
                    while (reader.Read())
                    {
                        if (reader.TokenType == JsonTokenType.EndArray) break;
                        T val = JsonSerializer.Deserialize<T>(ref reader);
                        if (val != null) list.Add(val);
                    }
                    return list.ToArray();
                }
                
                public delegate T[] ParseArrayDelegate<T>(ref Utf8JsonReader reader);

                public static TCollection ReadNestedCollection<TElement, TCollection>(
                    ref Utf8JsonReader reader, 
                    ParseArrayDelegate<TElement> parser)
                {
                    if (reader.TokenType == JsonTokenType.Null) return CreateCollectionInstance<TCollection, TElement>(null);
                    
                    TElement[] items = null;

                    if (reader.TokenType == JsonTokenType.StartArray)
                    {
                        items = parser(ref reader);
                    }
                    else if (reader.TokenType == JsonTokenType.StartObject)
                    {
                        var stored = reader;
                        bool found = false;
                        try 
                        {
                            while (reader.Read())
                            {
                                if (reader.TokenType == JsonTokenType.EndObject) break;
                                if (reader.TokenType == JsonTokenType.PropertyName)
                                {
                                    var propName = reader.GetString();
                                    if (propName == "records") 
                                    {
                                        reader.Read(); // StartArray
                                        items = parser(ref reader);
                                        found = true;
                                    }
                                    else
                                    {
                                        reader.Read(); // Move to Value
                                        TrySkip(ref reader); // Skip structure
                                    }
                                }
                            }
                        }
                        catch (System.Exception ex)
                        {
                            System.Console.WriteLine($"Error in ReadNestedCollection: {ex}");
                            throw;
                        }
                        
                        if (!found)
                        {
                            // Not found logic (restore?)
                        }
                    }
                    else 
                    {
                        TrySkip(ref reader);
                    }

                    return CreateCollectionInstance<TCollection, TElement>(items);
                }

                public static TCollection CreateCollectionInstance<TCollection, TElement>(TElement[] elements)
                {
                    if (elements == null) elements = System.Array.Empty<TElement>();
                    
                    if (typeof(TCollection).IsArray)
                    {
                        return (TCollection)(object)elements;
                    }

                    try
                    {
                        return (TCollection)System.Activator.CreateInstance(typeof(TCollection), new object[] { elements });
                    }
                    catch
                    {
                        var collection = System.Activator.CreateInstance<TCollection>();
                        if (collection is System.Collections.Generic.ICollection<TElement> genericCollection)
                        {
                            foreach (var element in elements) genericCollection.Add(element);
                        }
                        return collection;
                    }
                }

                public static System.DateTime SafeGetDateTime(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.String)
                    {
                        if (reader.TryGetDateTime(out var val)) return val;
                        var s = reader.GetString();
                        if (System.DateTime.TryParse(s, out var dt)) return dt;
                    }
                    return default;
                }

                public static System.DateTimeOffset SafeGetDateTimeOffset(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.String)
                    {
                        if (reader.TryGetDateTimeOffset(out var val)) return val;
                        var s = reader.GetString();
                        if (System.DateTimeOffset.TryParse(s, out var dto)) return dto;
                    }
                    return default;
                }

                public static string ReadStringCoerced(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.String) return reader.GetString();
                    if (reader.TokenType == JsonTokenType.Number) return reader.GetDecimal().ToString();
                    if (reader.TokenType == JsonTokenType.True) return "true";
                    if (reader.TokenType == JsonTokenType.False) return "false";
                    return null;
                }

                public static int ReadIntCoerced(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.Number) return reader.GetInt32();
                    if (reader.TokenType == JsonTokenType.String)
                    {
                        var s = reader.GetString();
                        if (int.TryParse(s, out var i)) return i;
                    }
                    return default;
                }

                public static long ReadLongCoerced(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.Number) return reader.GetInt64();
                    if (reader.TokenType == JsonTokenType.String)
                    {
                        var s = reader.GetString();
                        if (long.TryParse(s, out var l)) return l;
                    }
                    return default;
                }

                public static double ReadDoubleCoerced(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.Number) return reader.GetDouble();
                    if (reader.TokenType == JsonTokenType.String)
                    {
                        var s = reader.GetString();
                        if (double.TryParse(s, out var d)) return d;
                    }
                    return default;
                }

                public static decimal ReadDecimalCoerced(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.Number) return reader.GetDecimal();
                    if (reader.TokenType == JsonTokenType.String)
                    {
                        var s = reader.GetString();
                        if (decimal.TryParse(s, out var d)) return d;
                    }
                    return default;
                }

                public static bool ReadBoolCoerced(ref Utf8JsonReader reader)
                {
                    if (reader.TokenType == JsonTokenType.True) return true;
                    if (reader.TokenType == JsonTokenType.False) return false;
                    if (reader.TokenType == JsonTokenType.String)
                    {
                        var s = reader.GetString();
                        if (bool.TryParse(s, out var b)) return b;
                    }
                    if (reader.TokenType == JsonTokenType.Number)
                    {
                        return reader.GetInt32() != 0;
                    }
                    return default;
                }
            }
        }
        """;

        ctx.AddSource("SerializationHelpers.g.cs", SourceText.From(source, Encoding.UTF8));
        return ctx;
    }
}
