using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SoqlGen.Models;

namespace SoqlGen.Sources;

internal static partial class Texts
{
    internal const string SoqlCollection = nameof(SoqlCollection);
    private const string Indent = "                        ";

    public static (string? Source, Diagnostic? Diagnostic) GenerateSoqlCollectionSourceAndDiagnostic(
        QueryObject queryObject,
        Dictionary<(string ClassName, string Key), QueryObject> queryObjects)
    {
        var (query, diagnostic) = queryObject.GenerateQuery(queryObjects);

        if (query is null)
        {
            return (null, diagnostic);
        }

        var sourceText = $$"""
        // <auto-generated />
        // Generated by SoqlGen

        namespace {{nameof(SoqlGen)}};

        #nullable enable
        public static partial class {{nameof(SoqlCollection)}}
        {
            public static partial class {{queryObject.Key}}
            {
                public static class Model{{GetShortClassName(queryObject.ClassName)}}
                {
                    public const string Query = "{{query}}";
                    {{DeserializationMethodImpl(queryObject, queryObjects)}}
                }
            }
        }
        """;

        return (sourceText, diagnostic);
    }

    private static string DeserializationMethodImpl(QueryObject queryObject, Dictionary<(string ClassName, string Key), QueryObject> queryObjects) => $$"""
        public static {{queryObject.ClassName}}[] DeserializeSoqlResponse(string jsonResponse)
                    {
                        using var doc = System.Text.Json.JsonDocument.Parse(jsonResponse);
                        var root = doc.RootElement;

                        return DeserializeSoqlResponse(root);
                    }

                    public static {{queryObject.ClassName}}[] DeserializeSoqlResponse(System.Text.Json.JsonElement root)
                    {
                        if(root.ValueKind == System.Text.Json.JsonValueKind.Null)
                        {
                            return Array.Empty<{{queryObject.ClassName}}>();
                        }

                        if (!root.TryGetProperty("records", out var records))
                        {
                            var jsonArray = new System.Text.Json.Nodes.JsonArray { root };
                            records = System.Text.Json.JsonSerializer.SerializeToElement(jsonArray);
                        }

                        var recordCount = records.GetArrayLength();
                        var result = new {{queryObject.ClassName}}[recordCount];
                        for(var i = 0; i < recordCount; i++)
                        {
                            var record = records[i];
                            result[i] = new()
                            {
                                {{string.Join($"\n{Indent}", queryObject.Fields.Select(f =>
                                {
                                    var soqlPrefix = $"{nameof(SoqlCollection)}.{queryObject.Key}";
                                    var propAccessor = $"record.GetProperty(\"{f.FieldName}\")";

                                    // collectionType is the declared property type (e.g. List<Foo> or Foo[])
                                    var collectionType = f.TypeName.TrimEnd('?');
                                    // elementType is the inner/element type (Foo) for collections, or the type itself for non-collections
                                    var elementType = (f.IsCollection && f.CollectionBaseType is not null)
                                        ? f.CollectionBaseType.TrimEnd('?')
                                        : collectionType;

                                    // If elementType is not a generated model, use primitive deserialization directly
                                    if (!queryObjects.TryGetValue((elementType, queryObject.Key), out var _))
                                    {
                                        return $"{f.PropertyName} = {propAccessor}.ApplyOrDefault(static e => " + (elementType switch
                                        {
                                            "string" => "e.GetString()!",
                                            "int" or "Int32" => "e.GetInt32()",
                                            "long" or "Int64" => "e.GetInt64()",
                                            "bool" or "Boolean" => "e.GetBoolean()",
                                            "double" or "Double" => "e.GetDouble()",
                                            "decimal" or "Decimal" => "e.GetDecimal()",
                                            "DateTime" => "e.GetDateTime()",
                                            _ => $"({f.TypeName})System.Text.Json.JsonSerializer.Deserialize(e, typeof({elementType}))!"
                                        }) + "),";
                                    }

                                    var deserializationSyntax = $"{soqlPrefix}.Model{GetShortClassName(elementType)}.DeserializeSoqlResponse({propAccessor})";

                                    if (f.IsCollection)
                                    {
                                        if (collectionType.EndsWith("[]"))
                                        {
                                            return $"{f.PropertyName} = {deserializationSyntax},";
                                        }
                                        // create an instance of the collection type, passing the deserialized element array
                                        return $"{f.PropertyName} = ({f.TypeName})System.Activator.CreateInstance(typeof({collectionType}), new object[] {{ {deserializationSyntax} ?? default! }})!,";
                                    }
                                    // non-collection: take first element from deserialized element-array
                                    return $"{f.PropertyName} = {deserializationSyntax}.FirstOrDefault(),";
                                }))}}
                            };
                        }

                        return result;
                    }
        """;

    private static string GetShortClassName(string className) => className.Substring(className.LastIndexOf('.') + 1);

    public static InitializationContext AddSoqlCollectionSource(this InitializationContext ctx)
    {
        var source = $$"""
        // <auto-generated />
        // Generated by SoqlGen

        namespace {{nameof(SoqlGen)}};

        #nullable enable
        public static partial class {{nameof(SoqlCollection)}}
        {
            internal static T ApplyOrDefault<T>(this System.Text.Json.JsonElement element, Func<System.Text.Json.JsonElement, T> apply)
            {
                if(element.ValueKind is System.Text.Json.JsonValueKind.Null)
                {
                    return default!;
                }
                return apply(element);
            }
        }
        """;
        ctx.AddSource($"{nameof(SoqlCollection)}.g.cs", SourceText.From(source, Encoding.UTF8));
        return ctx;
    }
}
public static partial class Somethinf
{
    internal static T ApplyOrDefault<T>(this string element, Func<string, T> apply)
    {
        if (element.Length > 0)
        {
            return default!;
        }
        return apply(element);
    }
}
