using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace SoqlGen.Sources;

internal static partial class Texts
{
    public const string SoqlObjectAttribute = $$"""
    // <auto-generated />
    // Generated by SoqlGen
    
    namespace {{nameof(SoqlGen)}};

    #nullable enable
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = true)]
    public sealed class {{nameof(SoqlObjectAttribute)}} : System.Attribute
    {
        public {{nameof(SoqlObjectAttribute)}}(string rootObject, string key)
        {
            RootObject = rootObject;
            Key = key;
        }

        public string RootObject { get; }
        public string Key { get; }
    }
    """;

    public static InitializationContext AddSoqlObjectAttribute(this InitializationContext ctx)
    {
        ctx.AddSource($"{nameof(SoqlObjectAttribute)}.g.cs", SourceText.From(SoqlObjectAttribute, Encoding.UTF8));
        return ctx;
    }
}