using System.Text;
using Microsoft.CodeAnalysis.Text;
using SoqlGen; // For correct namespace if needed, but Texts is internal

namespace SoqlGen.Sources;

internal static partial class Texts
{
    public const string SoqlTypeHandling = $$"""
    // <auto-generated />
    // Generated by SoqlGen
    
    namespace {{nameof(SoqlGen)}}
    {
        public enum SoqlTypeHandling
        {
            Default = 0,
            Strict = 1,
            Coerce = 2
        }
    }
    """;

    public static InitializationContext AddSoqlTypeHandling(this InitializationContext ctx)
    {
        ctx.AddSource("SoqlTypeHandling.g.cs", SourceText.From(SoqlTypeHandling, Encoding.UTF8));
        return ctx;
    }
}
