using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SoqlGen.Models;
using System.Linq;

namespace SoqlGen.Sources;

internal static partial class Texts
{
    internal const string SoqlCollection = nameof(SoqlCollection);
    private const string Indent = "                        ";

    public static (string? Source, Diagnostic? Diagnostic) GenerateSoqlCollectionSourceAndDiagnostic(
        QueryObject queryObject,
        QueryDictionary queryObjects)
    {
        var (query, diagnostic) = queryObject.GenerateQuery(queryObjects);

        if (query is null)
        {
            return (null, diagnostic);
        }

        var sourceText = $$"""
        // <auto-generated />
        // Generated by SoqlGen

        namespace {{queryObject.Namespace}}
        {
            public partial class {{GetClassName(queryObject.ClassName)}}
            {
                public static partial class {{queryObject.Key}}
                {
                    public const string Query = "{{query}}";  
                    {{DeserializationMethodImpl(queryObject, queryObjects)}}
                }
            }
        }
        """;

        return (sourceText, diagnostic);
    }

    private static string DeserializationMethodImpl(QueryObject queryObject, QueryDictionary queryObjects)
    {
        var classFullName = queryObject.ClassName;
        var className = GetClassName(classFullName);
        
        return $$"""

                        /// <summary>
                        /// Deserializes a SOQL response from JSON string into a list of {{className}} objects.
                        /// Uses strict zero-allocation Utf8JsonReader.
                        /// </summary>
                        public static {{classFullName}}[] Deserialize(string jsonResponse)
                        {
                            if (string.IsNullOrEmpty(jsonResponse))
                            {
                                return System.Array.Empty{{(string.Equals(classFullName, className) ? "" : $"<{classFullName}>")}}();
                            }

                            var bytes = System.Text.Encoding.UTF8.GetBytes(jsonResponse);
                            var reader = new System.Text.Json.Utf8JsonReader(bytes);
                            return Deserialize(ref reader);
                        }

                        /// <summary>
                        /// Deserializes a SOQL response from UTF8 bytes into a list of {{className}} objects.
                        /// Uses strict zero-allocation Utf8JsonReader.
                        /// </summary>
                        public static {{classFullName}}[] Deserialize(System.ReadOnlySpan<byte> jsonBytes)
                        {
                            var reader = new System.Text.Json.Utf8JsonReader(jsonBytes);
                            return Deserialize(ref reader);
                        }

                        /// <summary>
                        /// Deserializes a SOQL response from Utf8JsonReader into a list of {{className}} objects.
                        /// </summary>
                        public static {{classFullName}}[] Deserialize(ref System.Text.Json.Utf8JsonReader reader)
                        {
                            if (reader.TokenType == System.Text.Json.JsonTokenType.None)
                            {
                                reader.Read();
                            }

                            if (reader.TokenType == System.Text.Json.JsonTokenType.StartArray)
                            {
                                return ParseArray(ref reader);
                            }

                            if (reader.TokenType != System.Text.Json.JsonTokenType.StartObject)
                            {
                                 return System.Array.Empty{{(string.Equals(classFullName, className) ? "" : $"<{classFullName}>")}}();
                            }
                            
                            // Lookahead mechanism: Store reader state
                            var storedReader = reader;
                            
                            {{classFullName}}[] result = System.Array.Empty{{(string.Equals(classFullName, className) ? "" : $"<{classFullName}>")}}();
                            bool recordsFound = false;

                            while (reader.Read())
                            {
                                if (reader.TokenType == System.Text.Json.JsonTokenType.EndObject)
                                {
                                    break;
                                }

                                if (reader.TokenType == System.Text.Json.JsonTokenType.PropertyName)
                                {
                                    var propName = reader.GetString();
                                    reader.Read(); // Move to value

                                    if (propName == "records")
                                    {
                                        result = ParseArray(ref reader);
                                        recordsFound = true;
                                    }
                                    else
                                    {
                                        SoqlGen.SerializationHelpers.TrySkip(ref reader);
                                    }
                                }
                            }

                            if (!recordsFound)
                            {
                                // Fallback: Restore reader and parse as single object
                                reader = storedReader;
                                var single = DeserializeSingleRecord(ref reader);
                                return new[] { single };
                            }

                            return result;
                        }

                        public static {{classFullName}}[] ParseArray(ref System.Text.Json.Utf8JsonReader reader)
                        {
                            if (reader.TokenType != System.Text.Json.JsonTokenType.StartArray)
                            {
                                 if (reader.TokenType == System.Text.Json.JsonTokenType.Null) return System.Array.Empty{{(string.Equals(classFullName, className) ? "" : $"<{classFullName}>")}}();
                                 SoqlGen.SerializationHelpers.TrySkip(ref reader);
                                 return System.Array.Empty{{(string.Equals(classFullName, className) ? "" : $"<{classFullName}>")}}();
                            }

                            var list = new System.Collections.Generic.List<{{classFullName}}>();
                            while (reader.Read())
                            {
                                if (reader.TokenType == System.Text.Json.JsonTokenType.EndArray)
                                {
                                    break;
                                }
                                
                                if (reader.TokenType == System.Text.Json.JsonTokenType.StartObject)
                                {
                                    list.Add(DeserializeSingleRecord(ref reader));
                                }
                                else
                                {
                                    SoqlGen.SerializationHelpers.TrySkip(ref reader); 
                                }
                            }
                            return list.ToArray();
                        }

                        public static {{classFullName}} DeserializeSingleRecord(ref System.Text.Json.Utf8JsonReader reader)
                        {
                            if (reader.TokenType == System.Text.Json.JsonTokenType.Null) return null;
                            var obj = new {{classFullName}}();
                            
                            while (reader.Read())
                            {
                                if (reader.TokenType == System.Text.Json.JsonTokenType.EndObject)
                                {
                                    break;
                                }

                                if (reader.TokenType == System.Text.Json.JsonTokenType.PropertyName)
                                {
                                    var propName = reader.GetString();
                                    reader.Read(); // Value

                                    switch (propName)
                                    {
        {{GeneratePropertySwitchCases(queryObject, queryObjects)}}
                                        default:
                                            SoqlGen.SerializationHelpers.TrySkip(ref reader);
                                            break;
                                    }
                                }
                            }

                            return obj;
                        }
        """;
    }

    private static string GeneratePropertySwitchCases(QueryObject queryObject, QueryDictionary queryObjects)
    {
        var sb = new StringBuilder();
        foreach (var field in queryObject.Fields)
        {
            sb.AppendLine($$"""
                                            case "{{field.FieldName}}":
                                                {{GeneratePropertyAssignment(field, queryObject, queryObjects)}}
                                                break;
            """);
        }
        return sb.ToString();
    }

    private static string GeneratePropertyAssignment(QueryField field, QueryObject parentObject, QueryDictionary queryObjects)
    {
        var propertyName = $"@{field.PropertyName}";

        var declaredPropertyType = field.TypeName.TrimEnd('?');
        var elementType = (field.IsCollection && field.CollectionBaseType is not null)
            ? field.CollectionBaseType.TrimEnd('?')
            : declaredPropertyType;
        
        // Use pre-calculated IsNullable from analyzer
        var isNullable = field.IsNullable;
        
        // Default=0, Strict=1, Coerce=2
        // If field is set (!=0), use it. Else if object is set (!=0), use it. Else default to Strict (1).
        var effectiveHandling = field.TypeHandling != 0 
            ? field.TypeHandling 
            : (parentObject.TypeHandling != 0 ? parentObject.TypeHandling : 1);

        if (!queryObjects.TryGetValue((elementType, parentObject.Key), out var _))
        {
            // Primitive
            var readLogic = GetPrimitiveReader(elementType, isNullable, effectiveHandling);
            
             if (field.IsCollection)
            {
                if (declaredPropertyType.EndsWith("[]"))
                {
                   return $"obj.{propertyName} = SoqlGen.SerializationHelpers.ReadPrimitiveArray<{elementType}>(ref reader) ?? System.Array.Empty<{elementType}>();";
                }
                return $"obj.{propertyName} = SoqlGen.SerializationHelpers.CreateCollectionInstance<{declaredPropertyType}, {elementType}>(SoqlGen.SerializationHelpers.ReadPrimitiveArray<{elementType}>(ref reader));";
            }
            
            return $"obj.{propertyName} = {readLogic};";
        }

        // Nested Model
        // In embedded design, the child object also has the same Query Key if it's part of the same query retrieval structure.
        // However, if the child object is defined separately, we access it via its class name.
        // But wait, the child object logic is now INSIDE the child object class.
        // So we call ChildClass.QueryKey.DeserializeSingleRecord
        
        // IMPORTANT: We need to know the 'Query Key' for the child object. 
        // In the current architecture, we assume all objects in the graph share the same 'Query Key' ("MyQuery").
        // So we can assume: {elementType}.{parentObject.Key}.DeserializeSingleRecord
        
        var childLogicClass = $"{elementType}.{parentObject.Key}";

        if (field.IsCollection)
        {
            // We use inline logic for nested collection to avoid delegate issues
            return $$"""
                obj.{{propertyName}} = SoqlGen.SerializationHelpers.ReadNestedCollection<{{elementType}}, {{declaredPropertyType}}>(ref reader, {{childLogicClass}}.ParseArray);
            """;
        }

        return $"obj.{propertyName} = {childLogicClass}.DeserializeSingleRecord(ref reader);";
    }

    private static string GetPrimitiveReader(string typeName, bool isNullable, int typeHandling)
    {
        var coreType = typeName.TrimEnd('?');
        var defaultVal = isNullable ? "null" : "default";

        // Coerce = 2
        if (typeHandling == 2)
        {
            var coercedCall = coreType switch
            {
                "string" or "System.String" => "SoqlGen.SerializationHelpers.ReadStringCoerced(ref reader)",
                "int" or "Int32" or "System.Int32" => "SoqlGen.SerializationHelpers.ReadIntCoerced(ref reader)",
                "long" or "Int64" or "System.Int64" => "SoqlGen.SerializationHelpers.ReadLongCoerced(ref reader)",
                "bool" or "Boolean" or "System.Boolean" => "SoqlGen.SerializationHelpers.ReadBoolCoerced(ref reader)",
                "double" or "Double" or "System.Double" => "SoqlGen.SerializationHelpers.ReadDoubleCoerced(ref reader)",
                "decimal" or "Decimal" or "System.Decimal" => "SoqlGen.SerializationHelpers.ReadDecimalCoerced(ref reader)",
                _ => null
            };

            if (coercedCall != null)
            {
                return coercedCall;
            }
            // Fallback to strict for unhandled types
        }

        var readerCall = coreType switch
        {
            "string" or "System.String" => "reader.GetString()", 
            "int" or "Int32" or "System.Int32" => $"(reader.TokenType == System.Text.Json.JsonTokenType.Number ? reader.GetInt32() : {defaultVal})",
            "long" or "Int64" or "System.Int64" => $"(reader.TokenType == System.Text.Json.JsonTokenType.Number ? reader.GetInt64() : {defaultVal})",
            "bool" or "Boolean" or "System.Boolean" => $"(reader.TokenType == System.Text.Json.JsonTokenType.True || reader.TokenType == System.Text.Json.JsonTokenType.False ? reader.GetBoolean() : {defaultVal})",
            "double" or "Double" or "System.Double" => $"(reader.TokenType == System.Text.Json.JsonTokenType.Number ? reader.GetDouble() : {defaultVal})",
            "decimal" or "Decimal" or "System.Decimal" => $"(reader.TokenType == System.Text.Json.JsonTokenType.Number ? reader.GetDecimal() : {defaultVal})",
            "float" or "Single" or "System.Single" => $"(reader.TokenType == System.Text.Json.JsonTokenType.Number ? reader.GetSingle() : {defaultVal})",
            "System.DateTime" or "DateTime" => "SoqlGen.SerializationHelpers.SafeGetDateTime(ref reader)",
            "System.DateTimeOffset" or "DateTimeOffset" => "SoqlGen.SerializationHelpers.SafeGetDateTimeOffset(ref reader)",
            "Guid" or "System.Guid" => "reader.GetGuid()",
            _ => $"System.Text.Json.JsonSerializer.Deserialize<{coreType}>(ref reader)" 
        };

        if (coreType == "string")
        {
            return $"(reader.TokenType == System.Text.Json.JsonTokenType.Null ? null : {readerCall})";
        }
        
        if (isNullable && coreType != "string" && !readerCall.Contains("Deserialize"))
        {
            // Inline null check
            return $"(reader.TokenType == System.Text.Json.JsonTokenType.Null ? null : {readerCall})";
        }

        return readerCall;
    }

    private static string GetClassName(string className) =>
        className.Substring(className.LastIndexOf('.') + 1).TrimEnd('?');

    public static InitializationContext AddSoqlCollectionSource(this InitializationContext ctx)
    {
        // No wrapper source needed anymore since logic is embedded in partial classes
        // The individual sources are added in GenerateSoqlCollectionSourceAndDiagnostic via context.AddSource
        return ctx;
    }
}
